services:
  postgres:
    image: postgres:16
    container_name: purchases-db
    restart: always
    environment:
      POSTGRES_DB: purchases
      POSTGRES_USER: purchases
      POSTGRES_PASSWORD: purchases
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: